services:
  #nextjs service
  nextapp:
    container_name: ghostlink-nextapp
    image: nextapp:1.0.0
    build:
      context: ./ghostlink-frontend
      dockerfile: next.dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./ghostlink-frontend/.env.local
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - flaskapp

  # backend service
  flaskapp:
    container_name: ghostlink-flaskapp
    image: flaskapp:3.0.3
    build:
      context: ./ghostlink-backend
      dockerfile: flask.dockerfile
    ports:
      - 4000:4000
    env_file:
      - ./ghostlink-backend/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
