"""add wiatlist model and update our db schemas

Revision ID: 72783afc1d32
Revises: f43a02c53ee2
Create Date: 2024-08-31 17:48:17.301688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72783afc1d32'
down_revision = 'f43a02c53ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waitlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_waitlisted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waitlist', schema=None) as batch_op:
        batch_op.drop_column('is_waitlisted')

    # ### end Alembic commands ###
