"""added is_waitlisted column to user

Revision ID: f43a02c53ee2
Revises: 
Create Date: 2024-08-31 15:20:36.465291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43a02c53ee2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_waitlisted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###

    # Remove the server_default to clean up the schema
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_waitlisted', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_waitlisted')

    # ### end Alembic commands ###
