import AvatarSection from "./sections/avatar";
import TextAreaSection from "./sections/text";
import IconsSection from "./sections/icons";
import PostButtonSection from "./sections/post";

// these should realistaclly not be any and we should fix this
interface PostMockUpProps {
  linkedInPost4o: any; // Replace 'any' with the appropriate type if known
  linkedInPost4oMini: any; // Replace 'any' with the appropriate type if known
}

const PostMockUp = ({
  linkedInPost4o,
  linkedInPost4oMini,
}: PostMockUpProps) => {
  return (
    <div className="flex flex-row gap-5">
      <div className="flex flex-col">
        <h1 className="mb-2 ml-3 mt-10 text-lg text-white">Generated by 4o:</h1>
        <div className="flex h-[600px] w-[730px] flex-col rounded-xl border bg-white">
          <AvatarSection />
          <TextAreaSection linkedInPost={linkedInPost4o} />
          <IconsSection />
          <PostButtonSection />
        </div>
      </div>

      <div className="flex flex-col">
        <h1 className="mb-2 ml-3 mt-10 text-lg text-white">
          Generated by 4o Mini:
        </h1>
        <div className="flex h-[600px] w-[730px] flex-col rounded-xl border bg-white">
          <AvatarSection />
          <TextAreaSection linkedInPost={linkedInPost4oMini} />
          <IconsSection />
          <PostButtonSection />
        </div>
      </div>
    </div>
  );
};

export default PostMockUp;
