// PostMockUp.tsx
import AvatarSection from "./sections/avatar";
import IconsSection from "./sections/icons";
import PostButtonSection from "./sections/post";
import React from "react";

interface PostMockUpProps {
  linkedInPost4o: React.ReactNode; // Use ReactNode to accept JSX content
  linkedInPost4oMini: React.ReactNode;
}

const PostMockUp = ({ linkedInPost4o, linkedInPost4oMini }: PostMockUpProps) => {
  return (
    <div className="flex flex-col lg:flex-row gap-10 p-5 lg:p-10">
      <div className="flex flex-col items-stretch">
        <h1 className="mb-4 text-center text-lg text-white">Generated by 4o:</h1>
        <div className="flex flex-col rounded-xl border bg-white p-4 space-y-4 h-[85vh] w-full lg:w-[45vw]">
          <AvatarSection />
          <div className="flex-grow overflow-y-auto">{linkedInPost4o}</div>
          <IconsSection />
          <PostButtonSection />
        </div>
      </div>

      <div className="flex flex-col items-stretch">
        <h1 className="mb-4 text-center text-lg text-white">
          Generated by 4o Mini:
        </h1>
        <div className="flex flex-col rounded-xl border bg-white p-4 space-y-4 h-[85vh] w-full lg:w-[45vw]">
          <AvatarSection />
          <div className="flex-grow overflow-y-auto">{linkedInPost4oMini}</div>
          <IconsSection />
          <PostButtonSection />
        </div>
      </div>
    </div>
  );
};

export default PostMockUp;
